apiVersion: v1
kind: Service
metadata:
  labels:
    app: staticcv
  name: staticcv
  namespace: default
spec:
  type: NodePort
  ports:
  - name: "staticcv"
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    app: staticcv